import type {
  IssueDetailEnvelope,
  IssueSearchEnvelope,
} from "../shared/api/generated";

const evidence = {
  description: "Repository language matches the contributor profile.",
  ruleId: "skill.repository-language",
  source: "repository_language" as const,
};

export const issueSearchFixture: IssueSearchEnvelope = {
  data: {
    contributionProfile: {
      cacheHit: false,
      status: "partial",
      version: "v1",
    },
    items: [
      {
        difficulty: {
          confidence: "high",
          label: "Intermediate",
          level: 3,
        },
        effort: {
          band: "half_day",
          confidence: "medium",
          label: "Half a day",
        },
        healthSummary: [
          { name: "activity", score: 92, status: "available" },
          { name: "community", score: 81, status: "partial" },
          { name: "beginner_friendly", score: 74, status: "partial" },
          { name: "security", score: null, status: "unavailable" },
        ],
        issue: {
          comments: 4,
          createdAt: "2026-07-01T00:00:00Z",
          estimatedDifficulty: 3,
          labels: ["good first issue", "accessibility"],
          number: 42,
          title: "Improve keyboard navigation in the command palette",
          updatedAt: "2026-07-29T00:00:00Z",
          url: "https://github.com/octocat/typed-service/issues/42",
        },
        recommendation: {
          breakdown: [
            {
              maximum: 30,
              name: "skill_match",
              reasons: ["TypeScript is a profile skill."],
              score: 25,
            },
            {
              maximum: 20,
              name: "issue_quality",
              reasons: ["The issue has acceptance criteria."],
              score: 18,
            },
            {
              maximum: 15,
              name: "activity",
              reasons: ["The repository is active."],
              score: 12,
            },
            {
              maximum: 15,
              name: "maintainer_responsiveness",
              reasons: ["Maintainers respond to contributors."],
              score: 10,
            },
            {
              maximum: 10,
              name: "repository_quality",
              reasons: ["CI and contribution docs are present."],
              score: 8,
            },
            {
              maximum: 10,
              name: "availability",
              reasons: ["The issue is open and unassigned."],
              score: 10,
            },
          ],
          claim: {
            claimed: false,
            confidence: "high",
            evidence: [],
          },
          maintainerResponse: {
            confidence: "medium",
            firstIssueResponse: {
              confidence: "medium",
              medianSeconds: 21_600,
              percentile90Seconds: 43_200,
              sampleSize: 4,
              status: "available",
              truncated: false,
              windowDays: 180,
            },
            firstPullReview: {
              confidence: "medium",
              medianSeconds: 86_400,
              percentile90Seconds: 172_800,
              sampleSize: 3,
              status: "available",
              truncated: false,
              windowDays: 180,
            },
            label: "Very responsive",
            level: 5,
            pullRequestMerge: {
              confidence: "medium",
              medianSeconds: 207_360,
              percentile90Seconds: 345_600,
              sampleSize: 3,
              status: "available",
              truncated: false,
              windowDays: 180,
            },
            responseCoverage: {
              confidence: "medium",
              denominator: 4,
              numerator: 3,
              percentage: 75,
              sampleSize: 4,
              status: "available",
              truncated: false,
              windowDays: 180,
            },
            sampleSize: 7,
            status: "available",
            windowDays: 180,
          },
          reasons: [
            "The primary language matches your profile.",
            "The issue has clear acceptance criteria.",
          ],
          score: 83,
          skillMatch: {
            denominator: 2,
            matched: 1,
            partial: 0,
            percentage: 50,
            personalized: true,
            skills: [
              {
                confidence: "high",
                contributorEvidence: [evidence],
                requirementEvidence: [],
                status: "matched",
                technology: "TypeScript",
              },
              {
                confidence: "low",
                contributorEvidence: [],
                requirementEvidence: [],
                status: "unknown",
                technology: "Accessibility",
              },
            ],
            status: "partial",
            version: "v1",
          },
          stale: {
            analyzedAt: "2026-07-30T00:00:00Z",
            confidence: "high",
            evidence: [
              {
                description: "Recent maintainer activity was observed.",
                ruleId: "stale.maintainer.recent",
                source: "derived",
              },
            ],
            freshWithinDays: 30,
            issueCreatedAt: "2026-07-01T00:00:00Z",
            issueUpdatedAt: "2026-07-29T00:00:00Z",
            lastLinkedPullRequestAt: null,
            lastMaintainerActivityAt: "2026-07-29T00:00:00Z",
            lastMeaningfulIssueActivityAt: "2026-07-29T00:00:00Z",
            policyVersion: "stale-v1",
            repositoryActivityAt: "2026-07-29T12:00:00Z",
            sampleSize: 4,
            staleAfterDays: 180,
            state: "fresh",
            truncated: false,
          },
          warnings: [
            {
              code: "maintainer_sample_partial",
              evidence: [],
              message: "Maintainer response evidence is partial.",
              severity: "warning",
            },
          ],
        },
        repository: {
          description: "A typed service",
          fullName: "octocat/typed-service",
          isArchived: false,
          lastUpdatedAt: "2026-07-29T00:00:00Z",
          mainLanguage: "TypeScript",
          name: "typed-service",
          owner: "octocat",
          stars: 1250,
          url: "https://github.com/octocat/typed-service",
        },
      },
    ],
    pagination: {
      hasNext: true,
      page: 1,
      perPage: 20,
      total: 21,
      totalPages: 2,
    },
    searchSummary: {
      candidatesChecked: 50,
      enrichmentAttempted: 20,
      enrichmentFailed: 1,
      excludedByReason: [
        {
          count: 12,
          reason: "below_minimum_stars",
        },
      ],
      upstreamTotal: 1200,
    },
    warnings: [
      {
        code: "issue_enrichment_incomplete",
        message: "One repository used candidate metadata.",
      },
    ],
  },
  meta: {
    rateLimitRemaining: 4920,
    requestId: "req_issue_search",
    timestamp: "2026-07-30T00:00:00Z",
  },
};

export const issueDetailFixture: IssueDetailEnvelope = {
  data: {
    activity: {
      ci: "success",
      contributors: {
        confidence: "high",
        sampleSize: 24,
        status: "available",
        truncated: false,
        value: 8,
        windowDays: 90,
      },
      issueResponse: {
        confidence: "medium",
        medianSeconds: 7200,
        percentile90Seconds: 86_400,
        sampleSize: 18,
        status: "available",
        truncated: false,
        windowDays: 90,
      },
      lastMeaningfulUpdate: "2026-07-29T00:00:00Z",
      pullRequestMerge: {
        confidence: "high",
        denominator: 20,
        numerator: 15,
        percentage: 75,
        sampleSize: 20,
        status: "available",
        truncated: false,
        windowDays: 90,
      },
      pullRequestMergeTime: {
        confidence: "medium",
        medianSeconds: 172_800,
        percentile90Seconds: 432_000,
        sampleSize: 15,
        status: "available",
        truncated: false,
        windowDays: 90,
      },
      pullRequestReview: {
        confidence: "medium",
        medianSeconds: 14_400,
        percentile90Seconds: 172_800,
        sampleSize: 16,
        status: "available",
        truncated: false,
        windowDays: 90,
      },
      pullRequestsOpened: {
        confidence: "high",
        sampleSize: 20,
        status: "available",
        truncated: false,
        value: 20,
        windowDays: 90,
      },
      staleOpenPullRequests: {
        confidence: "medium",
        sampleSize: 7,
        status: "available",
        truncated: false,
        value: 2,
        windowDays: 90,
      },
      unansweredIssues: {
        confidence: "medium",
        sampleSize: 28,
        status: "available",
        truncated: true,
        value: 3,
        windowDays: 90,
      },
    },
    analysis: {
      category: {
        confidence: "high",
        evidence: [
          {
            description: "The title describes keyboard accessibility.",
            ruleId: "category.accessibility",
            source: "title",
          },
        ],
        matches: ["accessibility", "ui", "testing"],
        primary: "accessibility",
      },
      confidence: "high",
      difficulty: {
        confidence: "high",
        evidence: [
          {
            description: "The change crosses UI behavior and tests.",
            ruleId: "difficulty.cross-cutting",
            source: "derived",
          },
        ],
        label: "Intermediate",
        level: 3,
      },
      effort: {
        band: "half_day",
        confidence: "medium",
        evidence: [
          {
            description: "The described scope fits a focused half-day change.",
            ruleId: "effort.scope",
            source: "derived",
          },
        ],
        label: "Half a day",
      },
      quality: {
        confidence: "high",
        score: 82,
        signals: [
          {
            evidence: [
              {
                description: "The body explains the keyboard trap.",
                ruleId: "quality.problem-description",
                source: "body",
              },
            ],
            key: "problem_description",
            state: "present",
          },
          {
            evidence: [],
            key: "current_behavior",
            state: "present",
          },
          {
            evidence: [],
            key: "expected_behavior",
            state: "present",
          },
          {
            evidence: [],
            key: "reproduction_steps",
            state: "present",
          },
          {
            evidence: [],
            key: "acceptance_criteria",
            state: "present",
          },
          {
            evidence: [],
            key: "implementation_guidance",
            state: "unknown",
          },
          {
            evidence: [],
            key: "related_files",
            state: "present",
          },
          {
            evidence: [],
            key: "test_method",
            state: "present",
          },
          {
            evidence: [],
            key: "screenshot",
            state: "not_applicable",
          },
        ],
      },
      requiredTechnologies: [
        {
          confidence: "high",
          evidence: [evidence],
          kind: "language",
          name: "TypeScript",
        },
        {
          confidence: "high",
          evidence: [
            {
              description: "The affected interface is built with React.",
              ruleId: "technology.react",
              source: "body",
            },
          ],
          kind: "framework",
          name: "React",
        },
        {
          confidence: "medium",
          evidence: [
            {
              description: "The issue requires keyboard interaction testing.",
              ruleId: "technology.accessibility",
              source: "derived",
            },
          ],
          kind: "practice",
          name: "Accessibility testing",
        },
      ],
      scope: {
        areas: ["frontend", "tests"],
        confidence: "high",
        databaseChange: "not_applicable",
        evidence: [
          {
            description: "The body names a UI component and its tests.",
            ruleId: "scope.frontend-tests",
            source: "body",
          },
        ],
        fileCount: {
          label: "3–5 files",
          maximum: 5,
          minimum: 3,
        },
      },
    },
    healthDashboard: {
      analyzedAt: "2026-07-30T00:00:00Z",
      categories: [
        {
          analyzedAt: "2026-07-30T00:00:00Z",
          components: [
            {
              description: "Recent repository updates.",
              key: "recency",
              score: 100,
              source: "github",
              status: "available",
              weight: 50,
            },
          ],
          confidence: "high",
          name: "activity",
          score: 94,
          status: "available",
          warnings: [],
        },
        {
          analyzedAt: "2026-07-30T00:00:00Z",
          components: [
            {
              description: "Observed contributors.",
              key: "contributors",
              score: 80,
              source: "github",
              status: "available",
              weight: 35,
            },
          ],
          confidence: "medium",
          name: "community",
          score: 81,
          status: "partial",
          warnings: [],
        },
        {
          analyzedAt: "2026-07-30T00:00:00Z",
          components: [
            {
              description: "Contribution guidance.",
              key: "contributing_guide",
              score: 100,
              source: "github",
              status: "available",
              weight: 30,
            },
          ],
          confidence: "high",
          name: "beginner_friendly",
          score: 86,
          status: "available",
          warnings: [],
        },
        {
          analyzedAt: "2026-07-29T00:00:00Z",
          components: [
            {
              description: "Heuristic OpenSSF Scorecard check: Maintained.",
              key: "maintained",
              score: 90,
              source: "openssf_scorecard",
              status: "available",
              weight: 25,
            },
          ],
          confidence: "medium",
          name: "security",
          score: 82,
          sourceVersion: "v5.2.1",
          status: "partial",
          warnings: [
            "OpenSSF Scorecard observations are heuristics, not a security certification.",
          ],
        },
      ],
      scoreVersion: "2026-08-01",
    },
    inspection: {
      incomplete: false,
    },
    issue: {
      assignees: [],
      author: {
        login: "hubot",
        type: "User",
      },
      body: [
        "## Current behavior",
        "Tab focus can become trapped inside the command palette.",
        "",
        "## Acceptance criteria",
        "- Escape closes the palette",
        "- Focus returns to the trigger",
        "- Add keyboard interaction tests",
      ].join("\n"),
      comments: 4,
      createdAt: "2026-07-01T00:00:00Z",
      labels: ["good first issue", "accessibility"],
      locked: false,
      number: 42,
      state: "open",
      title: "Improve keyboard navigation in the command palette",
      updatedAt: "2026-07-29T00:00:00Z",
      url: "https://github.com/octocat/typed-service/issues/42",
    },
    recommendation: issueSearchFixture.data.items[0]!.recommendation,
    repository: {
      defaultBranch: "main",
      description: "A typed service",
      forks: 84,
      fullName: "octocat/typed-service",
      id: 123_456,
      isArchived: false,
      isFork: false,
      mainLanguage: "TypeScript",
      name: "typed-service",
      openIssues: 32,
      owner: "octocat",
      pushedAt: "2026-07-29T00:00:00Z",
      stars: 1250,
      updatedAt: "2026-07-29T00:00:00Z",
      url: "https://github.com/octocat/typed-service",
    },
    repositoryHealth: [
      {
        evidence: [],
        key: "readme",
        state: "present",
      },
      {
        evidence: [],
        key: "contributing",
        state: "present",
      },
      {
        evidence: [],
        key: "code_of_conduct",
        state: "present",
      },
      {
        evidence: [],
        key: "ci",
        state: "present",
      },
      {
        evidence: [],
        key: "tests",
        state: "present",
      },
    ],
  },
  meta: {
    rateLimitRemaining: 4910,
    requestId: "req_issue_detail",
    timestamp: "2026-07-30T00:00:00Z",
  },
};
