import { Download, FileText, Image } from "lucide-react";

import { Button } from "../../../components/ui/button";
import { Icon } from "../../../components/ui/icon";
import type {
  GitHubUser,
  ProfileAnalysis,
} from "../../../shared/api/generated";
import { useI18n } from "../../../shared/i18n/i18n-context";
import { profileCardLines, profileMarkdown } from "../model/profile-export";

export function ProfileShareActions({
  analysis,
  user,
}: {
  analysis: ProfileAnalysis;
  user: GitHubUser;
}) {
  const { t } = useI18n();
  const filename = `issuescout-${user.login.toLowerCase()}`;
  return (
    <section
      className="mt-5 flex flex-wrap items-center gap-3 rounded-xl border border-border bg-muted/30 p-4"
      aria-label={t("profile.exportTitle")}
    >
      <span className="mr-auto inline-flex items-center gap-2 text-sm font-semibold">
        <Icon icon={Download} /> {t("profile.exportTitle")}
      </span>
      <Button
        onClick={() =>
          downloadText(`${filename}.md`, profileMarkdown(user, analysis))
        }
        size="small"
        variant="outline"
      >
        <Icon icon={FileText} /> {t("profile.exportMarkdown")}
      </Button>
      <Button
        onClick={() => downloadPNG(`${filename}.png`, user, analysis)}
        size="small"
      >
        <Icon icon={Image} /> {t("profile.exportPng")}
      </Button>
    </section>
  );
}

function downloadText(filename: string, content: string) {
  downloadBlob(
    filename,
    new Blob([content], { type: "text/markdown;charset=utf-8" }),
  );
}

function downloadPNG(
  filename: string,
  user: GitHubUser,
  analysis: ProfileAnalysis,
) {
  const canvas = document.createElement("canvas");
  canvas.width = 1200;
  canvas.height = 630;
  const context = canvas.getContext("2d");
  if (!context) return;
  const content = profileCardLines(user, analysis);
  const gradient = context.createLinearGradient(0, 0, 1200, 630);
  gradient.addColorStop(0, "#071b24");
  gradient.addColorStop(1, "#103a42");
  context.fillStyle = gradient;
  context.fillRect(0, 0, 1200, 630);
  context.fillStyle = "#6ee7cf";
  context.font = "600 26px system-ui, sans-serif";
  context.fillText("IssueScout · Public OSS profile", 72, 72);
  context.fillStyle = "#f4fbfa";
  context.font = "700 58px system-ui, sans-serif";
  context.fillText(content.heading.slice(0, 32), 72, 155);
  context.fillStyle = "#a8c9c7";
  context.font = "28px system-ui, sans-serif";
  context.fillText(content.login, 72, 198);
  context.fillStyle = "#f4fbfa";
  context.font = "600 30px system-ui, sans-serif";
  context.fillText(content.merged, 72, 270);
  context.fillText(content.streak, 72, 316);
  context.fillStyle = "#6ee7cf";
  context.font = "600 23px system-ui, sans-serif";
  context.fillText(content.technologies.join("  ·  ").slice(0, 72), 72, 382);
  context.fillStyle = "#d8e9e7";
  context.font = "24px system-ui, sans-serif";
  content.journey.forEach((line, index) =>
    context.fillText(`• ${line}`.slice(0, 78), 72, 445 + index * 38),
  );
  context.fillStyle = "#86aaa8";
  context.font = "18px system-ui, sans-serif";
  context.fillText(
    "Bounded public GitHub evidence · generated by IssueScout",
    72,
    590,
  );
  canvas.toBlob((blob) => {
    if (blob) downloadBlob(filename, blob);
  }, "image/png");
}

function downloadBlob(filename: string, blob: Blob) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
